<a href="https://colab.research.google.com/github/haeniKim/metaverse-academy/blob/master/ML/230613_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##주성분 분석

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [ ]:
app=np.array([8,10,9,7,6,3,2,4,6,2,8,7])
per=np.array([1,7,9,5,4,5,1,2,4,5,6,7])

In [ ]:
data=np.array([app,per])
data=data.T
data

array([[ 8,  1],
       [10,  7],
       [ 9,  9],
       [ 7,  5],
       [ 6,  4],
       [ 3,  5],
       [ 2,  1],
       [ 4,  2],
       [ 6,  4],
       [ 2,  5],
       [ 8,  6],
       [ 7,  7]])

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
data_scaled=ss.fit_transform(data)
data_scaled

array([[ 0.77459667, -1.55563492],
       [ 1.54919334,  0.98994949],
       [ 1.161895  ,  1.83847763],
       [ 0.38729833,  0.14142136],
       [ 0.        , -0.28284271],
       [-1.161895  ,  0.14142136],
       [-1.54919334, -1.55563492],
       [-0.77459667, -1.13137085],
       [ 0.        , -0.28284271],
       [-1.54919334,  0.14142136],
       [ 0.77459667,  0.56568542],
       [ 0.38729833,  0.98994949]])

In [ ]:
cov=np.cov(data_scaled.T) #공분산 행
cov

array([[1.09090909, 0.56763974],
       [0.56763974, 1.09090909]])

In [ ]:
eig_value, eig_vector=np.linalg.eig(cov)
eig_value

array([0.52326935, 1.65854883])

In [ ]:
eig_value[1]/(eig_value[0]+eig_value[1])

0.7601682148149539

In [ ]:
eig_value[1]

1.658548832323536

In [ ]:
eig_vector

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [ ]:
eig_vector[1]

array([ 0.70710678, -0.70710678])

In [ ]:
favor=data_scaled.dot(eig_vector[1]) #dot 벡터의 내접.
favor

array([ 1.64772256,  0.39544512, -0.47841616,  0.17386128,  0.2       ,
       -0.92158384,  0.00455488,  0.25227744,  0.2       , -1.19544512,
        0.14772256, -0.42613872])

In [ ]:
data

array([[ 8,  1],
       [10,  7],
       [ 9,  9],
       [ 7,  5],
       [ 6,  4],
       [ 3,  5],
       [ 2,  1],
       [ 4,  2],
       [ 6,  4],
       [ 2,  5],
       [ 8,  6],
       [ 7,  7]])

In [ ]:
John=np.array([3,9])
Tom=np.array([5,2])

In [ ]:
John.reshape(-1,1)

array([[3],
       [9]])

In [ ]:
John_scaled=(John-np.mean(data))/np.std(data)
John_scaled

array([-0.91132238,  1.43207802])

In [ ]:
John_favor=John_scaled.dot(eig_vector[1].T)
John_favor

-1.657034312216982

In [ ]:
Tom_scaled=(Tom-np.mean(data))/np.std(data)
Tom_scaled

array([-0.13018891, -1.30188911])

In [ ]:
Tom_favor=Tom_scaled.dot(eig_vector[1].T)
Tom_favor

0.8285171561084912