<a href="https://colab.research.google.com/github/haeniKim/metaverse-academy/blob/master/DL/230710_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 67.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 39.5 MB/s eta 0:00:00


In [ ]:
from konlpy.tag import Okt
from nltk.tokenize import word_tokenize
from collections import Counter

In [ ]:
okt = Okt()

In [ ]:
text_data = '''
인도네시아 맥도날드가 웨딩 패키지를 출시했다. 결혼식 피로연용으로 구성된 햄버거와 맥너겟 세트다.

10일(현지시간) CBS에 따르면 인도네시아 맥도날드는 지난달 사회관계망서비스(SNS)를 통해 웨딩 패키지를 공개했다. 이 패키지는 치킨버거 1개와 맥너겟 4조각이 한 세트다. 기본은 100인분으로, 가격은 350만 인도네시아 루피다. 이를 한화로 환산하면 26만원 안팎이다.

CNBC는 알뜰한 신혼부부라면 이 패키지를 선택해 1인당 2달러(약 3000원) 수준으로 하객들에게 식사 메뉴를 제공할 수 있는 셈이라고 전했다. 다만 맥도날드 매장을 결혼식이나 피로연장으로 이용할 수는 없다.

한편 맥도날드가 웨딩 패키지 제품을 출시한 것은 이번이 처음은 아니다. 앞서 지난 2011년 홍콩 맥도날드 지점은 웨딩 케이크와 구디백(파티 참가자에게 보답용으로 주는 선물 가방) 등이 포함된 웨딩 패키지를 1300달러(약 169만원)에 판매한 바 있다.
'''

In [ ]:
text = okt.nouns(text_data)
text

['인도네시아',
 '맥도날드',
 '웨딩',
 '패키지',
 '출시',
 '결혼식',
 '피로연',
 '용',
 '구성',
 '햄버거',
 '맥너겟',
 '세트',
 '현지',
 '시간',
 '인도네시아',
 '맥도날드',
 '지난달',
 '사회',
 '관계',
 '망',
 '서비스',
 '를',
 '통해',
 '웨딩',
 '패키지',
 '공개',
 '이',
 '패키지',
 '치킨',
 '버거',
 '개',
 '맥너겟',
 '세트',
 '기본',
 '인분',
 '가격',
 '인도네시아',
 '루피',
 '한화',
 '환산',
 '안팎',
 '신혼부부',
 '라면',
 '이',
 '패키지',
 '선택',
 '약',
 '수준',
 '하객',
 '식사',
 '메뉴',
 '제공',
 '수',
 '셈',
 '전',
 '다만',
 '맥도날드',
 '매장',
 '결혼식',
 '피로연',
 '이용',
 '수',
 '한편',
 '맥도날드',
 '웨딩',
 '패키지',
 '제품',
 '출시',
 '것',
 '이번',
 '처음',
 '앞서',
 '지난',
 '홍콩',
 '맥도날드',
 '지점',
 '웨딩',
 '케이크',
 '디',
 '파티',
 '참가자',
 '보답',
 '용',
 '선물',
 '가방',
 '등',
 '포함',
 '웨딩',
 '패키지',
 '약',
 '판매',
 '바']

In [ ]:
words_freq = Counter(text)

In [ ]:
words_cleaned = [(w, c) for w,c in words_freq.items() if c >= 1]
words_cleaned.sort(key = lambda x: x[1], reverse = True)

In [ ]:
words_cleaned

[('패키지', 6),
 ('맥도날드', 5),
 ('웨딩', 5),
 ('인도네시아', 3),
 ('출시', 2),
 ('결혼식', 2),
 ('피로연', 2),
 ('용', 2),
 ('맥너겟', 2),
 ('세트', 2),
 ('이', 2),
 ('약', 2),
 ('수', 2),
 ('구성', 1),
 ('햄버거', 1),
 ('현지', 1),
 ('시간', 1),
 ('지난달', 1),
 ('사회', 1),
 ('관계', 1),
 ('망', 1),
 ('서비스', 1),
 ('를', 1),
 ('통해', 1),
 ('공개', 1),
 ('치킨', 1),
 ('버거', 1),
 ('개', 1),
 ('기본', 1),
 ('인분', 1),
 ('가격', 1),
 ('루피', 1),
 ('한화', 1),
 ('환산', 1),
 ('안팎', 1),
 ('신혼부부', 1),
 ('라면', 1),
 ('선택', 1),
 ('수준', 1),
 ('하객', 1),
 ('식사', 1),
 ('메뉴', 1),
 ('제공', 1),
 ('셈', 1),
 ('전', 1),
 ('다만', 1),
 ('매장', 1),
 ('이용', 1),
 ('한편', 1),
 ('제품', 1),
 ('것', 1),
 ('이번', 1),
 ('처음', 1),
 ('앞서', 1),
 ('지난', 1),
 ('홍콩', 1),
 ('지점', 1),
 ('케이크', 1),
 ('디', 1),
 ('파티', 1),
 ('참가자', 1),
 ('보답', 1),
 ('선물', 1),
 ('가방', 1),
 ('등', 1),
 ('포함', 1),
 ('판매', 1),
 ('바', 1)]

In [ ]:
word_to_index = { word[0] : index+1 for index,word in enumerate(words_cleaned)}
word_to_index

{'패키지': 1,
 '맥도날드': 2,
 '웨딩': 3,
 '인도네시아': 4,
 '출시': 5,
 '결혼식': 6,
 '피로연': 7,
 '용': 8,
 '맥너겟': 9,
 '세트': 10,
 '이': 11,
 '약': 12,
 '수': 13,
 '구성': 14,
 '햄버거': 15,
 '현지': 16,
 '시간': 17,
 '지난달': 18,
 '사회': 19,
 '관계': 20,
 '망': 21,
 '서비스': 22,
 '를': 23,
 '통해': 24,
 '공개': 25,
 '치킨': 26,
 '버거': 27,
 '개': 28,
 '기본': 29,
 '인분': 30,
 '가격': 31,
 '루피': 32,
 '한화': 33,
 '환산': 34,
 '안팎': 35,
 '신혼부부': 36,
 '라면': 37,
 '선택': 38,
 '수준': 39,
 '하객': 40,
 '식사': 41,
 '메뉴': 42,
 '제공': 43,
 '셈': 44,
 '전': 45,
 '다만': 46,
 '매장': 47,
 '이용': 48,
 '한편': 49,
 '제품': 50,
 '것': 51,
 '이번': 52,
 '처음': 53,
 '앞서': 54,
 '지난': 55,
 '홍콩': 56,
 '지점': 57,
 '케이크': 58,
 '디': 59,
 '파티': 60,
 '참가자': 61,
 '보답': 62,
 '선물': 63,
 '가방': 64,
 '등': 65,
 '포함': 66,
 '판매': 67,
 '바': 68}

In [ ]:
sentence = '카카오브레인은 고도화된 기술모델을 가지고 있다.'

sentence_to_index = [word_to_index[word] for word in okt.nouns(sentence) if word in word_to_index]
sentence_to_index

[]

## Keras를 통한 구현

In [ ]:
from keras.preprocessing.text import Tokenizer

In [ ]:
text_data = '''시스템은 메타버스 환경을 통해 사고 징후를 실시간 모니터링 하고, AI 기술로 사고 예방 및 사후 대응을 위한 최적의 의사결정을 지원해 피해규모를 최소화한다.

과기정통부는 디지털 기반의 사고 예방·대응 시스템 개발과 실증을 2025년까지 3년간 지원한다. 올해는 국비 80억원, 지방비 40억원 등 총 120억원을 투입한다.

충청북도에서는 산업단지를 중심으로 화재·폭발 등 대규모 사고 위험이 높은 산업 현장의 안전 강화를 추진한다. 기업별 제조 환경에 따른 맞춤형 고위험 사고 예방·관리 AI 솔루션과 생산 공정 전주기 안전관리 시스템 등을 개발 지원한다.'''

In [ ]:
text = okt.nouns(text_data)
text

['시스템',
 '메타',
 '버스',
 '환경',
 '통해',
 '사고',
 '징후',
 '실시간',
 '모니터링',
 '기술',
 '사고',
 '예방',
 '및',
 '사후',
 '대응',
 '위',
 '최적',
 '의사결정',
 '지원',
 '피해',
 '규모',
 '최소',
 '과',
 '정통부',
 '디지털',
 '기반',
 '사고',
 '예방',
 '대응',
 '시스템',
 '개발',
 '실증',
 '지원',
 '올해',
 '국비',
 '방비',
 '등',
 '총',
 '투입',
 '충청북도',
 '산업',
 '단지',
 '중심',
 '화재',
 '폭발',
 '등',
 '대규모',
 '사고',
 '위험',
 '산업',
 '현장',
 '안전',
 '강화',
 '추진',
 '기업',
 '별',
 '제조',
 '환경',
 '맞춤',
 '위험',
 '사고',
 '예방',
 '관리',
 '솔루션',
 '생산',
 '공정',
 '주기',
 '안전',
 '관리',
 '시스템',
 '등',
 '개발',
 '지원']

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_data)

In [ ]:
print(tokenizer.word_index)

{'사': 1, '고': 2, '지': 3, '을': 4, '한': 5, '원': 6, '기': 7, '다': 8, '시': 9, '스': 10, '해': 11, '를': 12, '방': 13, '의': 14, '0': 15, '템': 16, '모': 17, '예': 18, '대': 19, '위': 20, '정': 21, '화': 22, '과': 23, '는': 24, '·': 25, '발': 26, '2': 27, '억': 28, '등': 29, '산': 30, '업': 31, '전': 32, '은': 33, '환': 34, '경': 35, '통': 36, '후': 37, '실': 38, '간': 39, 'a': 40, 'i': 41, '로': 42, '응': 43, '최': 44, '규': 45, '개': 46, '년': 47, '비': 48, '에': 49, '험': 50, '안': 51, '관': 52, '리': 53, '메': 54, '타': 55, '버': 56, '징': 57, '니': 58, '터': 59, '링': 60, '하': 61, '술': 62, '및': 63, '적': 64, '결': 65, '피': 66, '소': 67, '부': 68, '디': 69, '털': 70, '반': 71, '증': 72, '5': 73, '까': 74, '3': 75, '올': 76, '국': 77, '8': 78, '4': 79, '총': 80, '1': 81, '투': 82, '입': 83, '충': 84, '청': 85, '북': 86, '도': 87, '서': 88, '단': 89, '중': 90, '심': 91, '으': 92, '재': 93, '폭': 94, '이': 95, '높': 96, '현': 97, '장': 98, '강': 99, '추': 100, '진': 101, '별': 102, '제': 103, '조': 104, '따': 105, '른': 106, '맞': 107, '춤': 108, '형': 109, '솔': 110, '루': 11

In [ ]:
sentence = '카카오브레인은 고도화된 기술을 가지고 있다.'
st = okt.nouns(sentence)
print(st)
print(tokenizer.texts_to_sequences([st]))

['카카오', '브레인', '고도화', '기술', '가지']
[[]]


In [ ]:
#ChatGPT 같은 대용량의 경우 모든 단어에 대한 처리가 필

## Padding

In [ ]:
import numpy as np
from keras.preprocessing.text import Tokenizer

In [ ]:
#정수인코딩 과정을 거침
text_data = '''
과학기술정보통신부는 충청권 4개 지자체와 디지털 기술을 활용한 재난안전관리 시스템을 구축하는 '인공지능(AI)·메타버스 기반 재난안전관리체계 강화' 사업을 추진한다고 9일 밝혔다.

시스템은 메타버스 환경을 통해 사고 징후를 실시간 모니터링 하고, AI 기술로 사고 예방 및 사후 대응을 위한 최적의 의사결정을 지원해 피해규모를 최소화한다.

과기정통부는 디지털 기반의 사고 예방·대응 시스템 개발과 실증을 2025년까지 3년간 지원한다. 올해는 국비 80억원, 지방비 40억원 등 총 120억원을 투입한다.

충청북도에서는 산업단지를 중심으로 화재·폭발 등 대규모 사고 위험이 높은 산업 현장의 안전 강화를 추진한다. 기업별 제조 환경에 따른 맞춤형 고위험 사고 예방·관리 AI 솔루션과 생산 공정 전주기 안전관리 시스템 등을 개발 지원한다.

충청남도에서는 교통사고 다발구역을 대상으로 사고 유발요소를 탐지하는 도로안전 관리 AI 솔루션을 개발한다. 또 인파사고 등을 예방·관리하는 생활안전 관리 AI 솔루션, 공공데이터와 연계한 도로·생활안전 통합관제시스템을 마련한다.
'''
text = okt.nouns(text_data)
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text)

In [ ]:
text_data = text_data.replace('\n','')
text_result = text_data.split('.')

text_result

["과학기술정보통신부는 충청권 4개 지자체와 디지털 기술을 활용한 재난안전관리 시스템을 구축하는 '인공지능(AI)·메타버스 기반 재난안전관리체계 강화' 사업을 추진한다고 9일 밝혔다",
 '시스템은 메타버스 환경을 통해 사고 징후를 실시간 모니터링 하고, AI 기술로 사고 예방 및 사후 대응을 위한 최적의 의사결정을 지원해 피해규모를 최소화한다',
 '과기정통부는 디지털 기반의 사고 예방·대응 시스템 개발과 실증을 2025년까지 3년간 지원한다',
 ' 올해는 국비 80억원, 지방비 40억원 등 총 120억원을 투입한다',
 '충청북도에서는 산업단지를 중심으로 화재·폭발 등 대규모 사고 위험이 높은 산업 현장의 안전 강화를 추진한다',
 ' 기업별 제조 환경에 따른 맞춤형 고위험 사고 예방·관리 AI 솔루션과 생산 공정 전주기 안전관리 시스템 등을 개발 지원한다',
 '충청남도에서는 교통사고 다발구역을 대상으로 사고 유발요소를 탐지하는 도로안전 관리 AI 솔루션을 개발한다',
 ' 또 인파사고 등을 예방·관리하는 생활안전 관리 AI 솔루션, 공공데이터와 연계한 도로·생활안전 통합관제시스템을 마련한다',
 '']

In [ ]:
encoding_data = []
for temp in text_result:
  temp = temp.strip() #각 문장 공백 제거 후
  st = okt.nouns(temp) #명사 값만 담기
  encoding_data.append(tokenizer.texts_to_sequences([st])[0]) #정수 인코딩 변환?

print(encoding_data)

[[24, 25, 26, 27, 28, 10, 11, 29, 12, 1, 2, 4, 30, 31, 32, 13, 14, 15, 12, 1, 2, 33, 16, 34, 17, 35], [4, 13, 14, 18, 36, 3, 37, 38, 39, 11, 3, 5, 40, 41, 19, 42, 43, 44, 7, 45, 46, 47], [48, 49, 10, 15, 3, 5, 19, 4, 8, 50, 7], [51, 52, 53, 6, 54, 55], [56, 20, 57, 58, 59, 60, 6, 61, 3, 21, 20, 62, 1, 16, 17], [63, 64, 65, 18, 66, 21, 3, 5, 2, 9, 67, 68, 69, 1, 2, 4, 6, 8, 7], [70, 71, 72, 73, 74, 3, 75, 76, 77, 22, 1, 2, 9, 8], [78, 79, 3, 6, 5, 2, 23, 1, 2, 9, 80, 81, 22, 23, 1, 82, 83, 4, 84], []]


In [ ]:
max_len = max(len(item) for item in encoding_data)
print(max_len)

26


In [ ]:
#26개의 단어로 이루어진 문장이 가장 긺
for sentence in encoding_data:
  print(sentence)

[24, 25, 26, 27, 28, 10, 11, 29, 12, 1, 2, 4, 30, 31, 32, 13, 14, 15, 12, 1, 2, 33, 16, 34, 17, 35]
[4, 13, 14, 18, 36, 3, 37, 38, 39, 11, 3, 5, 40, 41, 19, 42, 43, 44, 7, 45, 46, 47]
[48, 49, 10, 15, 3, 5, 19, 4, 8, 50, 7]
[51, 52, 53, 6, 54, 55]
[56, 20, 57, 58, 59, 60, 6, 61, 3, 21, 20, 62, 1, 16, 17]
[63, 64, 65, 18, 66, 21, 3, 5, 2, 9, 67, 68, 69, 1, 2, 4, 6, 8, 7]
[70, 71, 72, 73, 74, 3, 75, 76, 77, 22, 1, 2, 9, 8]
[78, 79, 3, 6, 5, 2, 23, 1, 2, 9, 80, 81, 22, 23, 1, 82, 83, 4, 84]
[]


In [ ]:
for sentence in encoding_data:
  while len(sentence) < max_len: #0이 추가되기 때문에 따로 cnt 변수를 추가할 필요가 없음
    sentence.append(0)

In [ ]:
print(encoding_data)

[[24, 25, 26, 27, 28, 10, 11, 29, 12, 1, 2, 4, 30, 31, 32, 13, 14, 15, 12, 1, 2, 33, 16, 34, 17, 35], [4, 13, 14, 18, 36, 3, 37, 38, 39, 11, 3, 5, 40, 41, 19, 42, 43, 44, 7, 45, 46, 47, 0, 0, 0, 0], [48, 49, 10, 15, 3, 5, 19, 4, 8, 50, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [51, 52, 53, 6, 54, 55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [56, 20, 57, 58, 59, 60, 6, 61, 3, 21, 20, 62, 1, 16, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [63, 64, 65, 18, 66, 21, 3, 5, 2, 9, 67, 68, 69, 1, 2, 4, 6, 8, 7, 0, 0, 0, 0, 0, 0, 0], [70, 71, 72, 73, 74, 3, 75, 76, 77, 22, 1, 2, 9, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [78, 79, 3, 6, 5, 2, 23, 1, 2, 9, 80, 81, 22, 23, 1, 82, 83, 4, 84, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [ ]:
#keras - 패딩 패키지가 있음.
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
text_data = '''
과학기술정보통신부는 충청권 4개 지자체와 디지털 기술을 활용한 재난안전관리 시스템을 구축하는 '인공지능(AI)·메타버스 기반 재난안전관리체계 강화' 사업을 추진한다고 9일 밝혔다.

시스템은 메타버스 환경을 통해 사고 징후를 실시간 모니터링 하고, AI 기술로 사고 예방 및 사후 대응을 위한 최적의 의사결정을 지원해 피해규모를 최소화한다.

과기정통부는 디지털 기반의 사고 예방·대응 시스템 개발과 실증을 2025년까지 3년간 지원한다. 올해는 국비 80억원, 지방비 40억원 등 총 120억원을 투입한다.

충청북도에서는 산업단지를 중심으로 화재·폭발 등 대규모 사고 위험이 높은 산업 현장의 안전 강화를 추진한다. 기업별 제조 환경에 따른 맞춤형 고위험 사고 예방·관리 AI 솔루션과 생산 공정 전주기 안전관리 시스템 등을 개발 지원한다.

충청남도에서는 교통사고 다발구역을 대상으로 사고 유발요소를 탐지하는 도로안전 관리 AI 솔루션을 개발한다. 또 인파사고 등을 예방·관리하는 생활안전 관리 AI 솔루션, 공공데이터와 연계한 도로·생활안전 통합관제시스템을 마련한다.
'''

In [ ]:
text = okt.nouns(text_data)

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text)

In [ ]:
encoding_data = []
for temp in text_result:
  temp = temp.strip() #각 문장 공백 제거 후
  st = okt.nouns(temp) #명사 값만 담기
  encoding_data.append(tokenizer.texts_to_sequences([st])[0]) #정수 인코딩 변환?

print(encoding_data)

[[24, 25, 26, 27, 28, 10, 11, 29, 12, 1, 2, 4, 30, 31, 32, 13, 14, 15, 12, 1, 2, 33, 16, 34, 17, 35], [4, 13, 14, 18, 36, 3, 37, 38, 39, 11, 3, 5, 40, 41, 19, 42, 43, 44, 7, 45, 46, 47], [48, 49, 10, 15, 3, 5, 19, 4, 8, 50, 7], [51, 52, 53, 6, 54, 55], [56, 20, 57, 58, 59, 60, 6, 61, 3, 21, 20, 62, 1, 16, 17], [63, 64, 65, 18, 66, 21, 3, 5, 2, 9, 67, 68, 69, 1, 2, 4, 6, 8, 7], [70, 71, 72, 73, 74, 3, 75, 76, 77, 22, 1, 2, 9, 8], [78, 79, 3, 6, 5, 2, 23, 1, 2, 9, 80, 81, 22, 23, 1, 82, 83, 4, 84], []]


In [ ]:
padding = pad_sequences(encoding_data, padding = 'post', maxlen= 10, truncating = 'post') #maxlen = n, truncating = 'post' - 최대 길이 넘을 때 앞부분 살리기.
padding

array([[24, 25, 26, 27, 28, 10, 11, 29, 12,  1,  2,  4, 30, 31, 32, 13,
        14, 15, 12,  1,  2, 33, 16, 34, 17, 35],
       [ 4, 13, 14, 18, 36,  3, 37, 38, 39, 11,  3,  5, 40, 41, 19, 42,
        43, 44,  7, 45, 46, 47,  0,  0,  0,  0],
       [48, 49, 10, 15,  3,  5, 19,  4,  8, 50,  7,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [51, 52, 53,  6, 54, 55,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [56, 20, 57, 58, 59, 60,  6, 61,  3, 21, 20, 62,  1, 16, 17,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [63, 64, 65, 18, 66, 21,  3,  5,  2,  9, 67, 68, 69,  1,  2,  4,
         6,  8,  7,  0,  0,  0,  0,  0,  0,  0],
       [70, 71, 72, 73, 74,  3, 75, 76, 77, 22,  1,  2,  9,  8,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [78, 79,  3,  6,  5,  2, 23,  1,  2,  9, 80, 81, 22, 23,  1, 82,
        83,  4, 84,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 

In [ ]:
last_value = len(tokenizer.word_index) + 1
last_value

85

In [ ]:
padding = pad_sequences(encoding_data,truncating='post',padding='post',maxlen=10,value=last_value) #마지막 값으로 채우기
padding

array([[24, 25, 26, 27, 28, 10, 11, 29, 12,  1],
       [ 4, 13, 14, 18, 36,  3, 37, 38, 39, 11],
       [48, 49, 10, 15,  3,  5, 19,  4,  8, 50],
       [51, 52, 53,  6, 54, 55, 85, 85, 85, 85],
       [56, 20, 57, 58, 59, 60,  6, 61,  3, 21],
       [63, 64, 65, 18, 66, 21,  3,  5,  2,  9],
       [70, 71, 72, 73, 74,  3, 75, 76, 77, 22],
       [78, 79,  3,  6,  5,  2, 23,  1,  2,  9],
       [85, 85, 85, 85, 85, 85, 85, 85, 85, 85]], dtype=int32)

## One Hot Encoding

In [ ]:
# 5 : 0, 1, 2, 3, 4
#[[1,0,0,0,0],[0,0,0,0,1]]

In [ ]:
from konlpy.tag import Okt
okt = Okt()
text_data = okt.morphs('나는 오늘 파이썬을 공부하고 있습니다')
text_data

['나', '는', '오늘', '파이썬', '을', '공부', '하고', '있습니다']

In [ ]:
word_encoding = {word: index for index,word in enumerate(text_data)}
print(word_encoding)

{'나': 0, '는': 1, '오늘': 2, '파이썬': 3, '을': 4, '공부': 5, '하고': 6, '있습니다': 7}


In [ ]:
one_hot_vector = [0] * (len(word_encoding))
one_hot_vector

[0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
index = word_encoding['파이썬']
index

3

In [ ]:
one_hot_vector[index] = 1
one_hot_vector

[0, 0, 0, 1, 0, 0, 0, 0]

* keras를 사용한 One Hot Enocoding

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

In [ ]:
text = '나는 오늘 파이썬을 공부하고있습니다.'

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
tokenizer.word_index

{'나는': 1, '오늘': 2, '파이썬을': 3, '공부하고있습니다': 4}

In [ ]:
sentence = '나는 오늘 파이썬을 공부하고 있습니다.'
encoded = tokenizer.texts_to_sequences([sentence])[0]
encoded

[1, 2, 3]

In [ ]:
ont_hot = to_categorical(encoded)
print(ont_hot)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
